# Notebook OSeMOSYS — debug del flujo de la app

Notebook que usa **exclusivamente** las funciones de `app.simulation.core.*` (las mismas que la app productiva), para reproducir paso a paso lo que hace el backend y poder localizar dónde se introduce una discrepancia (ej. años faltantes).

Soporta tres modos:
- **A) Excel SAND** → `run_data_processing_from_excel`
- **B) Carpeta de CSVs** → `get_processing_result_from_csv_dir` + post-procesado
- **C) Base de datos** → `run_data_processing(db, scenario_id)`

Cada celda imprime estado clave para comparar con la app:
- conjunto YEAR (primer/último año, conteo)
- # tecnologías, regiones, fuels
- años en parámetros críticos
- años cargados en la instancia
- años presentes en los resultados

## 0. Bootstrap

Necesario para importar `from app.simulation.core import ...`. Añade `backend/` a `sys.path` y configura `GRB_LICENSE_FILE`.

In [14]:
import os, sys
from pathlib import Path

BACKEND_DIR = Path.cwd()
while BACKEND_DIR.name != "backend" and BACKEND_DIR.parent != BACKEND_DIR:
    BACKEND_DIR = BACKEND_DIR.parent
assert BACKEND_DIR.name == "backend", f"No encontre backend/ subiendo desde {Path.cwd()}"
REPO_ROOT = BACKEND_DIR.parent

if str(BACKEND_DIR) not in sys.path:
    sys.path.insert(0, str(BACKEND_DIR))
os.chdir(BACKEND_DIR)

_grb = REPO_ROOT / "secrets" / "gurobi.lic"
if _grb.is_file():
    os.environ["GRB_LICENSE_FILE"] = str(_grb)

print("cwd        :", os.getcwd())
print("backend    :", BACKEND_DIR)
print("GRB_LICENSE:", os.environ.get("GRB_LICENSE_FILE", "(no set)"))

cwd        : /Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend
backend    : /Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend
GRB_LICENSE: /Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/secrets/gurobi.lic

## 0.5 Explorar escenarios disponibles en BD

Antes de elegir el modo, listamos los escenarios existentes en `osemosys.scenario` con sus columnas clave + estadísticas de `osemosys_param_value` (filas, rango de años).

Útil para:
- Decidir qué `SCENARIO_ID` usar en modo BD.
- Ver de un vistazo si **algún escenario tiene años truncados en la BD** (compara `year_max` vs el rango del SAND original).
- Detectar templates / escenarios sin datos.

Si la BD no está accesible (`SessionLocal()` falla), salta esta sección y usa modo Excel/CSV.

In [15]:
import os
import pandas as pd
from sqlalchemy import create_engine, func, select
from sqlalchemy.orm import sessionmaker
from app.models.scenario import Scenario
from app.models.osemosys_param_value import OsemosysParamValue

# El .env del backend usa host "db" (red interna de Docker Compose). Desde el host,
# Postgres esta expuesto en 127.0.0.1:55432 (ver docker-compose.yml).
# Override-able via env var por si tu setup difiere.
DEFAULT_LOCAL_PG = "postgresql+psycopg://osemosys:osemosys@127.0.0.1:55432/osemosys"
NB_DB_URL = os.environ.get("OSEMOSYS_NB_DATABASE_URL", DEFAULT_LOCAL_PG)
print("Conectando a:", NB_DB_URL)

_nb_engine = create_engine(NB_DB_URL, future=True, pool_pre_ping=True)
NbSession = sessionmaker(bind=_nb_engine, autocommit=False, autoflush=False)


def list_scenarios() -> pd.DataFrame:
    """Devuelve un DataFrame con los escenarios + estadisticas de osemosys_param_value."""
    with NbSession() as db:
        scenarios = db.execute(
            select(
                Scenario.id, Scenario.name, Scenario.owner, Scenario.description,
                Scenario.simulation_type, Scenario.processing_mode, Scenario.is_template,
                Scenario.base_scenario_id, Scenario.edit_policy, Scenario.udc_config,
                Scenario.created_at,
            )
        ).all()

        stats_rows = db.execute(
            select(
                OsemosysParamValue.id_scenario,
                func.count().label("n_rows"),
                func.min(OsemosysParamValue.year).label("year_min"),
                func.max(OsemosysParamValue.year).label("year_max"),
            ).group_by(OsemosysParamValue.id_scenario)
        ).all()
    stats = {r.id_scenario: (r.n_rows, r.year_min, r.year_max) for r in stats_rows}

    rows = []
    for s in scenarios:
        n_rows, ymin, ymax = stats.get(s.id, (0, None, None))
        rows.append({
            "id": s.id,
            "name": s.name,
            "owner": s.owner,
            "simulation_type": s.simulation_type,
            "processing_mode": s.processing_mode,
            "is_template": s.is_template,
            "base_scenario_id": s.base_scenario_id,
            "udc_enabled": bool((s.udc_config or {}).get("enabled")) if s.udc_config else False,
            "edit_policy": s.edit_policy,
            "param_rows": int(n_rows or 0),
            "year_min": int(ymin) if ymin is not None else None,
            "year_max": int(ymax) if ymax is not None else None,
            "n_years": (int(ymax) - int(ymin) + 1) if (ymin is not None and ymax is not None) else 0,
            "created_at": s.created_at,
            "description": (s.description or "")[:60],
        })
    return pd.DataFrame(rows).sort_values("id").reset_index(drop=True)


df_scenarios = list_scenarios()
print(f"Escenarios en BD: {len(df_scenarios)}\n")
cols_show = [
    "id", "name", "owner", "simulation_type", "processing_mode",
    "udc_enabled", "param_rows", "year_min", "year_max", "n_years", "is_template", "base_scenario_id",
]
with pd.option_context("display.max_rows", 200, "display.width", 220, "display.max_colwidth", 50):
    print(df_scenarios[cols_show].to_string(index=False))

Conectando a: postgresql+psycopg://osemosys:osemosys@127.0.0.1:55432/osemosys
Escenarios en BD: 10

 id                      name   owner simulation_type processing_mode  udc_enabled  param_rows  year_min  year_max  n_years  is_template  base_scenario_id
  2        Caso Base Nacional    seed        NATIONAL        STANDARD        False      739536      2022      2055       34        False               NaN
  4                   PA - MR    seed        NATIONAL        STANDARD        False      752538      2022      2055       34        False               NaN
  5         PA - MR - w/o UDC    seed        NATIONAL        STANDARD        False      752538      2022      2055       34        False               4.0
  6 PA - MR - w/o UDC (copia) dbedoya        NATIONAL        STANDARD        False      752538      2022      2055       34        False               5.0
  7                    PD old    seed        NATIONAL        STANDARD        False      723066      2022      2055       34        False               NaN
  8                 PD sin MR    seed        NATIONAL        STANDARD        False      744374      2022      2055       34        False               NaN
  9                  PD 23 04    seed        NATIONAL        STANDARD        False      743490      2022      2055       34        False               NaN
 10                  CN 29 04    seed        NATIONAL        STANDARD        False      746392      2022      2055       34        False               NaN
 11                        CN    seed        NATIONAL        STANDARD        False      746392      2022      2055       34        False               NaN
 12      PD con incosistencia    seed        NATIONAL        STANDARD        False      741552      2022      2055       34        False               NaN

## 1. Selección de modo

Activa **uno** de los tres modos. La celda comprueba que solo uno esté activo.

In [80]:
# Modo A: Excel SAND
EXCEL_PATH: Path | None = Path("/Users/davidbedoya0/Downloads/29_04_26_SAND_INTEGRADO_CN_V2 _RM__Parameters_SAND.xlsx")
EXCEL_PATH: Path | None = Path('/Users/davidbedoya0/Downloads/PD 23 04 26 _ Test Correction Elec_Parameters_SAND-2.xlsx')
EXCEL_PATH: Path | None = Path('/Users/davidbedoya0/Downloads/29_04_26_SAND_INTEGRADO_CN_V2 _RM__Parameters_SAND.xlsx')
EXCEL_PATH: Path | None = None
# EXCEL_PATH: Path | None = None

# Modo B: carpeta de CSVs ya procesados
CSV_DIR_IN: Path | None = None        # ej. BACKEND_DIR / "tmp" / "run_notebook_clean"

# Modo C: BD (PostgreSQL) — requiere DATABASE_URL en .env
SCENARIO_ID: int | None = 13        # ej. 42

# Destino de CSVs si EXCEL_PATH activo
CSV_DIR_OUT: Path = BACKEND_DIR / "tmp" / "run_notebook_app"

active = sum(x is not None for x in (EXCEL_PATH, CSV_DIR_IN, SCENARIO_ID))
assert active == 1, f"Activa exactamente 1 modo (actual: {active})"

if EXCEL_PATH is not None:
    MODE = "excel"
elif CSV_DIR_IN is not None:
    MODE = "csv"
else:
    MODE = "db"

print("MODE             :", MODE)
print("EXCEL_PATH       :", EXCEL_PATH)
print("CSV_DIR_IN       :", CSV_DIR_IN)
print("SCENARIO_ID      :", SCENARIO_ID)
print("CSV_DIR_OUT      :", CSV_DIR_OUT)

MODE             : db
EXCEL_PATH       : None
CSV_DIR_IN       : None
SCENARIO_ID      : 13
CSV_DIR_OUT      : /Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/tmp/run_notebook_app

## 2. Etapa 1 — `data_processing` (BD/Excel/CSV → CSVs preparados + ProcessingResult)

Usa **exactamente** las funciones del app:

- Excel: `run_data_processing_from_excel(excel_path, csv_dir)`
- CSV: post-procesa con `reorder_activity_ratio_csvs_for_dataportal`, `normalize_mode_of_operation_in_csv_dir`, `strip_whitespace_in_set_csvs`, `eliminar_valores_fuera_de_indices` + `get_processing_result_from_csv_dir`
- DB: `run_data_processing(db, scenario_id, csv_dir)` — necesita `Session` SQLAlchemy

In [81]:
import time, shutil
from app.simulation.core.data_processing import (
    run_data_processing_from_excel,
    run_data_processing,
    get_processing_result_from_csv_dir,
    eliminar_valores_fuera_de_indices,
    normalize_mode_of_operation_in_csv_dir,
    reorder_activity_ratio_csvs_for_dataportal,
    strip_whitespace_in_set_csvs,
)

t0 = time.perf_counter()

if MODE == "excel":
    if CSV_DIR_OUT.exists():
        shutil.rmtree(CSV_DIR_OUT)
    CSV_DIR_OUT.mkdir(parents=True, exist_ok=True)
    proc_result = run_data_processing_from_excel(
        excel_path=EXCEL_PATH,
        csv_dir=str(CSV_DIR_OUT),
        sheet_name="Parameters",
        div=1,
    )
    csv_dir = str(CSV_DIR_OUT)

elif MODE == "csv":
    csv_dir = str(CSV_DIR_IN)
    # Mismo orden que run_osemosys_from_csv_dir
    reorder_activity_ratio_csvs_for_dataportal(csv_dir)
    normalize_mode_of_operation_in_csv_dir(csv_dir)
    strip_whitespace_in_set_csvs(csv_dir)
    eliminar_valores_fuera_de_indices(csv_dir)
    proc_result = get_processing_result_from_csv_dir(csv_dir)

elif MODE == "db":
    # Usamos NbSession (definido en la celda 0.5) para apuntar a 127.0.0.1:55432
    # en lugar del host 'db' que solo existe dentro de Docker Compose.
    if "NbSession" not in dir():
        raise RuntimeError(
            "MODE='db' requiere NbSession definido. Ejecuta primero la celda 0.5 "
            "(Explorar escenarios)."
        )
    if CSV_DIR_OUT.exists():
        shutil.rmtree(CSV_DIR_OUT)
    CSV_DIR_OUT.mkdir(parents=True, exist_ok=True)
    csv_dir = str(CSV_DIR_OUT)
    with NbSession() as db:
        proc_result = run_data_processing(db, scenario_id=SCENARIO_ID, csv_dir=csv_dir)

t_stage1 = time.perf_counter() - t0

print(f"\nEtapa 1 completada en {t_stage1:.2f} s")
print(f"  csv_dir : {csv_dir}")
print(f"  has_storage: {proc_result.has_storage}")
print(f"  has_udc    : {proc_result.has_udc}")
print(f"  param_count: {proc_result.param_count}")
print(f"  sets disponibles ({len(proc_result.sets)}): {sorted(proc_result.sets)}")

Etapa 1 completada en 9.53 s
  csv_dir : /Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/tmp/run_notebook_app
  has_storage: False
  has_udc    : False
  param_count: 743570
  sets disponibles (7): ['EMISSION', 'FUEL', 'MODE_OF_OPERATION', 'REGION', 'TECHNOLOGY', 'TIMESLICE', 'YEAR']

### 2.1 Inspección post-Etapa 1

Aquí está el **punto crítico** para debug de "años faltantes". Comprobamos:

1. Años en `proc_result.sets["YEAR"]` (lo que la app reportará).
2. Años presentes en `YEAR.csv`.
3. Años presentes en parámetros clave (DemandProfile, EmissionActivityRatio, etc.).
4. Diferencias entre CSVs.

Si la app no toma hasta 2055 pero los CSVs sí lo tienen, el filtro está aguas abajo (en `build_instance` o en `process_results`).

In [82]:
import pandas as pd
from pathlib import Path

csv_dir_p = Path(csv_dir)

# 1. proc_result.sets["YEAR"]
years_proc = sorted(proc_result.sets.get("YEAR", []))
print(f"proc_result.sets['YEAR']: {len(years_proc)} elementos")
print(f"  rango: {min(years_proc) if years_proc else None} -> {max(years_proc) if years_proc else None}")
print(f"  primeros: {years_proc[:5]}")
print(f"  ultimos : {years_proc[-5:]}")

# 2. YEAR.csv en disco
year_csv = csv_dir_p / "YEAR.csv"
if year_csv.exists():
    df_year = pd.read_csv(year_csv)
    print(f"\nYEAR.csv: {len(df_year)} filas")
    print(f"  rango: {df_year['VALUE'].min()} -> {df_year['VALUE'].max()}")
else:
    print("\nYEAR.csv NO existe")

# 3. Años presentes en parametros clave
print(f"\nAnos presentes en parametros (max year por archivo):")
critical = [
    "SpecifiedAnnualDemand.csv",
    "AccumulatedAnnualDemand.csv",
    "SpecifiedDemandProfile.csv",
    "EmissionActivityRatio.csv",
    "InputActivityRatio.csv",
    "OutputActivityRatio.csv",
    "CapitalCost.csv",
    "FixedCost.csv",
    "VariableCost.csv",
    "ResidualCapacity.csv",
    "AvailabilityFactor.csv",
    "CapacityFactor.csv",
]
for fname in critical:
    fp = csv_dir_p / fname
    if not fp.exists():
        print(f"  {fname:<35s} NO existe")
        continue
    df = pd.read_csv(fp, usecols=["YEAR"]) if "YEAR" in pd.read_csv(fp, nrows=0).columns else None
    if df is None or df.empty:
        print(f"  {fname:<35s} vacio o sin YEAR")
        continue
    print(f"  {fname:<35s} rango YEAR: {int(df['YEAR'].min())} -> {int(df['YEAR'].max())}, n={len(df)}")

# 4. Otros sets
for s in ("REGION", "TECHNOLOGY", "FUEL", "EMISSION", "MODE_OF_OPERATION", "TIMESLICE"):
    elems = proc_result.sets.get(s, [])
    print(f"\nproc_result.sets['{s}']: {len(elems)} elementos")
    if elems:
        print(f"  primeros: {list(elems)[:5]}")

proc_result.sets['YEAR']: 33 elementos
  rango: 2022 -> 2054
  primeros: [2022, 2023, 2024, 2025, 2026]
  ultimos : [2050, 2051, 2052, 2053, 2054]

YEAR.csv: 33 filas
  rango: 2022 -> 2054

Anos presentes en parametros (max year por archivo):
  SpecifiedAnnualDemand.csv           rango YEAR: 2022 -> 2054, n=2739
  AccumulatedAnnualDemand.csv         rango YEAR: 2022 -> 2054, n=3564
  SpecifiedDemandProfile.csv          rango YEAR: 2022 -> 2054, n=33
  EmissionActivityRatio.csv           rango YEAR: 2022 -> 2054, n=141900
  InputActivityRatio.csv              rango YEAR: 2022 -> 2054, n=12705
  OutputActivityRatio.csv             rango YEAR: 2022 -> 2054, n=352968
  CapitalCost.csv                     rango YEAR: 2022 -> 2054, n=13464
  FixedCost.csv                       rango YEAR: 2022 -> 2054, n=13464
  VariableCost.csv                    rango YEAR: 2022 -> 2054, n=13464
  ResidualCapacity.csv                rango YEAR: 2022 -> 2054, n=13464
  AvailabilityFactor.csv              rango YEAR: 2022 -> 2054, n=13464
  CapacityFactor.csv                  rango YEAR: 2022 -> 2054, n=12870

proc_result.sets['REGION']: 1 elementos
  primeros: ['RE1']

proc_result.sets['TECHNOLOGY']: 408 elementos
  primeros: ['BACKSTOP_1', 'BACKSTOP_2', 'BBGDST', 'DEMAGFDSL', 'DEMAGFELC']

proc_result.sets['FUEL']: 115 elementos
  primeros: ['ELC', 'ELC002', 'AGFHEA', 'AGFELC', 'CONSDSL']

proc_result.sets['EMISSION']: 11 elementos
  primeros: ['EMIBC', 'EMIC02', 'EMICH4', 'EMICO', 'EMICOVDM']

proc_result.sets['MODE_OF_OPERATION']: 1 elementos
  primeros: ['1']

proc_result.sets['TIMESLICE']: 1 elementos
  primeros: ['S101']

In [83]:
# =============================================================================
# DEBUG: comparar BD vs CSV generado para detectar discrepancias por
# reconciliacion de bounds lower/upper, drop_duplicates, etc.
# Solo aplica si MODE == "db".
# =============================================================================
if MODE != "db":
    print("Esta celda solo aplica en MODE='db' (cuando los datos vienen de la BD).")
else:
    from sqlalchemy import select
    from app.models.osemosys_param_value import OsemosysParamValue
    from app.models.technology import Technology
    from app.models.region import Region

    BOUND_PAIRS = [
        ("TotalTechnologyAnnualActivityLowerLimit", "TotalTechnologyAnnualActivityUpperLimit"),
        ("TotalAnnualMinCapacity", "TotalAnnualMaxCapacity"),
        ("TotalAnnualMinCapacityInvestment", "TotalAnnualMaxCapacityInvestment"),
    ]

    # 1) Caso concreto: PWRNGS_CS, 2027, TotalAnnualMinCapacityInvestment
    print("=" * 70)
    print("CASO PUNTUAL: PWRNGS_CS, 2027")
    print("=" * 70)

    with NbSession() as db:
        tech = db.execute(
            select(Technology).where(Technology.name == "PWRNGS_CS")
        ).scalar_one_or_none()
        if tech is None:
            print("PWRNGS_CS no existe en osemosys.technology")
        else:
            for pname in ("TotalAnnualMinCapacityInvestment", "TotalAnnualMaxCapacityInvestment"):
                rows = db.execute(
                    select(OsemosysParamValue).where(
                        OsemosysParamValue.id_scenario == SCENARIO_ID,
                        OsemosysParamValue.param_name == pname,
                        OsemosysParamValue.id_technology == tech.id,
                        OsemosysParamValue.year == 2027,
                    )
                ).scalars().all()
                if not rows:
                    print(f"  BD {pname:<45s} (PWRNGS_CS, 2027): SIN FILAS")
                else:
                    for r in rows:
                        print(f"  BD {pname:<45s} (PWRNGS_CS, 2027) = {r.value}")

    # 2) Mismo en CSV
    csv_dir_p = Path(csv_dir)
    for pname in ("TotalAnnualMinCapacityInvestment", "TotalAnnualMaxCapacityInvestment"):
        fp = csv_dir_p / f"{pname}.csv"
        if not fp.exists():
            print(f"  CSV {pname}: NO existe")
            continue
        df = pd.read_csv(fp)
        sub = df[(df["TECHNOLOGY"] == "PWRNGS_CS") & (df["YEAR"] == 2027)]
        if sub.empty:
            print(f"  CSV {pname:<44s} (PWRNGS_CS, 2027): SIN FILA")
        else:
            for _, r in sub.iterrows():
                print(f"  CSV {pname:<44s} (PWRNGS_CS, 2027) = {r['VALUE']}")

    # 3) Diff masivo: detectar TODOS los pares Min/Max donde la reconciliacion
    #    promediante haya alterado valores (lower > upper en BD).
    print()
    print("=" * 70)
    print("DETECCION GLOBAL: tuplas alteradas por reconciliacion bounds")
    print("=" * 70)

    # Cargar tecnologias / regiones para mapear ids -> nombre
    with NbSession() as db:
        tech_map = {t.id: t.name for t in db.execute(select(Technology)).scalars()}
        region_map = {r.id: r.name for r in db.execute(select(Region)).scalars()}

    def _load_bd(pname):
        with NbSession() as db:
            rows = db.execute(
                select(OsemosysParamValue).where(
                    OsemosysParamValue.id_scenario == SCENARIO_ID,
                    OsemosysParamValue.param_name == pname,
                )
            ).scalars().all()
        return [
            {
                "REGION": region_map.get(r.id_region, ""),
                "TECHNOLOGY": tech_map.get(r.id_technology, ""),
                "YEAR": int(r.year) if r.year is not None else None,
                "VALUE": float(r.value),
            }
            for r in rows
        ]

    for lower_name, upper_name in BOUND_PAIRS:
        lower_bd = pd.DataFrame(_load_bd(lower_name))
        upper_bd = pd.DataFrame(_load_bd(upper_name))
        if lower_bd.empty or upper_bd.empty:
            print(f"\n  {lower_name} vs {upper_name}: alguno vacio en BD, skip")
            continue
        # Mismas dimensiones: REGION, TECHNOLOGY, YEAR
        merged = lower_bd.merge(
            upper_bd, on=["REGION", "TECHNOLOGY", "YEAR"], suffixes=("_LOW", "_UPP")
        )
        violating = merged[merged["VALUE_LOW"] > merged["VALUE_UPP"]]
        print(f"\n  {lower_name} > {upper_name}: {len(violating)} tuplas afectadas en BD")
        if len(violating) > 0:
            sample = violating.head(15).copy()
            sample["MID"] = (sample["VALUE_LOW"] + sample["VALUE_UPP"]) / 2.0
            print("  Top 15 (estos valores quedan SOBRESCRITOS por el promedio en el CSV):")
            with pd.option_context("display.width", 200, "display.max_colwidth", 30):
                print(sample.to_string(index=False))

======================================================================
CASO PUNTUAL: PWRNGS_CS, 2027
======================================================================
  BD TotalAnnualMinCapacityInvestment              (PWRNGS_CS, 2027) = 0.0
  BD TotalAnnualMaxCapacityInvestment              (PWRNGS_CS, 2027) = 0.0
  CSV TotalAnnualMinCapacityInvestment             (PWRNGS_CS, 2027) = 0.0
  CSV TotalAnnualMaxCapacityInvestment             (PWRNGS_CS, 2027) = 0.0

======================================================================
DETECCION GLOBAL: tuplas alteradas por reconciliacion bounds
======================================================================

  TotalTechnologyAnnualActivityLowerLimit > TotalTechnologyAnnualActivityUpperLimit: 12 tuplas afectadas en BD
  Top 15 (estos valores quedan SOBRESCRITOS por el promedio en el CSV):
REGION       TECHNOLOGY  YEAR  VALUE_LOW  VALUE_UPP       MID
   RE1 DEMINDLPGBOI_LOW  2023   0.600333   0.600333  0.600333
   RE1           UPSBJS  2033   7.988289   7.988289  7.988289
   RE1           UPSBJS  2035  12.453640  12.453640 12.453640
   RE1           UPSBJS  2037  18.525991  18.525990 18.525991
   RE1           UPSBJS  2038  22.105322  22.105320 22.105321
   RE1           UPSBJS  2039  25.943611  25.943610 25.943611
   RE1           UPSBJS  2041  33.903363  33.903360 33.903361
   RE1           UPSBJS  2043  41.340763  41.340760 41.340762
   RE1           UPSBJS  2044  44.589024  44.589020 44.589022
   RE1           UPSBJS  2046  49.889262  49.889260 49.889261
   RE1           UPSBJS  2048  53.627145  53.627140 53.627142
   RE1           UPSBJS  2049  54.995472  54.995470 54.995471

  TotalAnnualMinCapacity > TotalAnnualMaxCapacity: 0 tuplas afectadas en BD

  TotalAnnualMinCapacityInvestment > TotalAnnualMaxCapacityInvestment: 1 tuplas afectadas en BD
  Top 15 (estos valores quedan SOBRESCRITOS por el promedio en el CSV):
REGION    TECHNOLOGY  YEAR  VALUE_LOW  VALUE_UPP       MID
   RE1 PWRSOLUGE_BAT  2028  32.135184        0.0 16.067592

## 3. Etapa 2 — `create_abstract_model`

`create_abstract_model(has_storage, has_udc)` declara sets, parámetros, variables, restricciones y objetivo. **No tiene datos todavía**.

In [84]:
from app.simulation.core.model_definition import create_abstract_model
from pyomo.environ import Set, Param, Var, Constraint, Objective

t0 = time.perf_counter()
model = create_abstract_model(
    has_storage=proc_result.has_storage,
    has_udc=proc_result.has_udc,
)
t_stage2 = time.perf_counter() - t0

def _count(ct):
    return sum(1 for _ in model.component_objects(ct, active=True))

print(f"Etapa 2 (create_abstract_model) completada en {t_stage2:.3f} s")
print(f"  Sets        : {_count(Set)}")
print(f"  Params      : {_count(Param)}")
print(f"  Vars        : {_count(Var)}")
print(f"  Constraints : {_count(Constraint)}")
print(f"  Objectives  : {_count(Objective)}")

Etapa 2 (create_abstract_model) completada en 0.005 s
  Sets        : 9
  Params      : 50
  Vars        : 30
  Constraints : 44
  Objectives  : 1

## 4. Etapa 3 — `build_instance`

`build_instance(model, csv_dir, has_storage, has_udc)` carga todos los CSVs vía `pyomo.DataPortal` y devuelve una `ConcreteModel`.

Si los años aparecen aquí pero no en los outputs después, el problema está en `process_results`.

In [85]:
from app.simulation.core.instance_builder import build_instance

t0 = time.perf_counter()
instance = build_instance(
    model,
    csv_dir,
    has_storage=proc_result.has_storage,
    has_udc=proc_result.has_udc,
)
t_stage3 = time.perf_counter() - t0

n_vars = sum(len(v) for v in instance.component_objects(Var, active=True))
n_cons = sum(len(c) for c in instance.component_objects(Constraint, active=True))

print(f"Etapa 3 (build_instance) completada en {t_stage3:.2f} s")
print(f"  # variables    : {n_vars}")
print(f"  # restricciones: {n_cons}")

           0 seconds to construct Set YEAR; 1 index total
           0 seconds to construct Set TECHNOLOGY; 1 index total
           0 seconds to construct Set TIMESLICE; 1 index total
           0 seconds to construct Set FUEL; 1 index total
           0 seconds to construct Set EMISSION; 1 index total
           0 seconds to construct Set MODE_OF_OPERATION; 1 index total
           0 seconds to construct Set REGION; 1 index total
           0 seconds to construct Set FLEXIBLEDEMANDTYPE; 1 index total
           0 seconds to construct Set UDC; 1 index total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param YearSplit; 33 indices total
           0 seconds to construct Param DiscountRate; 1 index total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param DiscountRateIdv; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param OperationalLife; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param CapitalRecoveryFactor; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param PvAnnuity; 408 indices total
           0 seconds to construct Param DepreciationMethod; 1 index total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.01 seconds to construct Param AccumulatedAnnualDemand; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param SpecifiedAnnualDemand; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param SpecifiedDemandProfile; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param Demand; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param CapacityToActivityUnit; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param CapacityFactor; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param AvailabilityFactor; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param ResidualCapacity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param InputActivityRatio; 1548360 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.65 seconds to construct Param OutputActivityRatio; 1548360 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param CapitalCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param VariableCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param FixedCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param CapacityOfOneTechnologyUnit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalAnnualMaxCapacity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalAnnualMinCapacity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalAnnualMaxCapacityInvestment; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalAnnualMinCapacityInvestment; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalTechnologyAnnualActivityUpperLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param TotalTechnologyAnnualActivityLowerLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TotalTechnologyModelPeriodActivityUpperLimit; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TotalTechnologyModelPeriodActivityLowerLimit; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param ReserveMarginTagTechnology; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param ReserveMarginTagFuel; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param ReserveMargin; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Param RETagTechnology; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param RETagFuel; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param REMinProductionTarget; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.26 seconds to construct Param EmissionActivityRatio; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param EmissionsPenalty; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param AnnualExogenousEmission; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param AnnualEmissionLimit; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param ModelPeriodExogenousEmission; 11 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param ModelPeriodEmissionLimit; 11 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param InputToNewCapacityRatio; 1548360 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param InputToTotalCapacityRatio; 1548360 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TechnologyActivityByModeLowerLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TechnologyActivityByModeUpperLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TechnologyActivityDecreaseByModeLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param TechnologyActivityIncreaseByModeLimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param EmissionToActivityChangeRatio; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param DisposalCostPerCapacity; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Param RecoveryValuePerCapacity; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var NumberOfNewTechnologyUnits; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var NewCapacity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var RateOfActivity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var VariableOperatingCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var SalvageValue; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedSalvageValue; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var OperatingCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var CapitalInvestment; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedCapitalInvestment; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedOperatingCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var AnnualVariableOperatingCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var AnnualFixedOperatingCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var TotalDiscountedCostByTechnology; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var TotalDiscountedCost; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var TotalCapacityInReserveMargin; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DemandNeedingReserveMargin; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var TotalREProductionAnnual; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var RETotalProductionOfTargetFuelAnnual; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var TotalTechnologyModelPeriodActivity; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.03 seconds to construct Var AnnualTechnologyEmissionByMode; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Var AnnualTechnologyEmission; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Var AnnualTechnologyEmissionPenaltyByEmission; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var AnnualTechnologyEmissionsPenalty; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedTechnologyEmissionsPenalty; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var AnnualEmissions; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var ModelPeriodEmissions; 11 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DisposalCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedDisposalCost; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var RecoveryValue; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Var DiscountedRecoveryValue; 13464 indices total
           0 seconds to construct Objective OBJ; 1 index total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint TotalNewCapacity_2; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.18 seconds to construct Constraint ConstraintCapacity; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.22 seconds to construct Constraint PlannedMaintenance; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        8.15 seconds to construct Constraint EnergyBalanceEachTS5; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        8.44 seconds to construct Constraint EnergyBalanceEachYear4; 3795 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.03 seconds to construct Constraint UndiscountedCapitalInvestment; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint DiscountedCapitalInvestment_constraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.03 seconds to construct Constraint OperatingCostsVariable; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.19 seconds to construct Constraint OperatingCostsFixedAnnual; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint OperatingCostsTotalAnnual; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint DiscountedOperatingCostsTotalAnnual; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.05 seconds to construct Constraint TotalDiscountedCostByTechnology_constraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.01 seconds to construct Constraint TotalDiscountedCost_constraint; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.17 seconds to construct Constraint TotalAnnualMaxCapacityConstraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.17 seconds to construct Constraint TotalAnnualMinCapacityConstraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.04 seconds to construct Constraint SalvageValueAtEndOfPeriod1; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint SalvageValueDiscountedToStartYear; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.01 seconds to construct Constraint TotalAnnualMaxNewCapacityConstraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.01 seconds to construct Constraint TotalAnnualMinNewCapacityConstraint; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.03 seconds to construct Constraint TotalAnnualTechnologyActivityUpperlimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.03 seconds to construct Constraint TotalAnnualTechnologyActivityLowerlimit; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint TotalModelHorizonTechnologyActivity; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint TotalModelHorizonTechnologyActivityUpperLimit; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint TotalModelHorizonTechnologyActivityLowerLimit; 408 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.23 seconds to construct Constraint AnnualEmissionProductionByMode; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.19 seconds to construct Constraint AnnualEmissionProduction; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.17 seconds to construct Constraint EmissionPenaltyByTechAndEmission; 148104 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.09 seconds to construct Constraint EmissionsPenaltyByTechnology; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint DiscountedEmissionsPenaltyByTechnology; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.08 seconds to construct Constraint EmissionsAccounting1; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint EmissionsAccounting2; 11 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint AnnualEmissionsLimit; 363 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint ModelPeriodEmissionsLimit; 11 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.17 seconds to construct Constraint ReserveMargin_TechnologiesIncluded; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        3.69 seconds to construct Constraint ReserveMargin_FuelsIncluded; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
           0 seconds to construct Constraint ReserveMarginConstraint; 33 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.02 seconds to construct Constraint LU1_TechnologyActivityByModeUL; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.04 seconds to construct Constraint LU2_TechnologyActivityByModeLL; 13464 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.13 seconds to construct Constraint LU3_TechnologyActivityIncreaseByMode; 444312 indices total
           0 seconds to construct Set SetProduct_OrderedSet; 1 index total
        0.13 seconds to construct Constraint LU4_TechnologyActivityDecreaseByMode; 444312 indices total

In [86]:
# Inspeccionar conjuntos cargados en la instancia (despues de DataPortal)
years_instance = sorted(int(y) for y in instance.YEAR)
print(f"instance.YEAR: {len(years_instance)} elementos")
print(f"  rango: {min(years_instance)} -> {max(years_instance)}")
print(f"  primeros: {years_instance[:5]}")
print(f"  ultimos : {years_instance[-5:]}")

# Comparar con proc_result
diff_proc_inst = set(years_proc) - set(years_instance)
diff_inst_proc = set(years_instance) - set(years_proc)
if diff_proc_inst or diff_inst_proc:
    print(f"\n!! DIFERENCIAS:")
    print(f"  en proc pero no en instance: {sorted(diff_proc_inst)}")
    print(f"  en instance pero no en proc: {sorted(diff_inst_proc)}")
else:
    print(f"\nOK: instance.YEAR == proc_result.sets['YEAR']")

# Otros sets
for set_name in ("REGION", "TECHNOLOGY", "FUEL", "EMISSION", "TIMESLICE", "MODE_OF_OPERATION"):
    set_obj = getattr(instance, set_name, None)
    if set_obj is None:
        print(f"\ninstance.{set_name}: NO EXISTE")
        continue
    elems = list(set_obj)
    print(f"instance.{set_name}: {len(elems)} elementos")

instance.YEAR: 33 elementos
  rango: 2022 -> 2054
  primeros: [2022, 2023, 2024, 2025, 2026]
  ultimos : [2050, 2051, 2052, 2053, 2054]

OK: instance.YEAR == proc_result.sets['YEAR']
instance.REGION: 1 elementos
instance.TECHNOLOGY: 408 elementos
instance.FUEL: 115 elementos
instance.EMISSION: 11 elementos
instance.TIMESLICE: 1 elementos
instance.MODE_OF_OPERATION: 1 elementos

In [87]:
# =============================================================================
# DEBUG ESPECIFICO: por que se pierde 2055 entre YEAR.csv y instance.YEAR
# =============================================================================
import pandas as pd
from pathlib import Path
from pyomo.environ import AbstractModel, Set, DataPortal

p = Path(csv_dir)

# 1) Volcado RAW de YEAR.csv (incluye whitespace y bytes especiales)
print("=" * 70)
print("YEAR.csv: contenido raw")
print("=" * 70)
with open(p / "YEAR.csv", "rb") as f:
    raw = f.read()
print(f"  bytes totales: {len(raw)}")
print(f"  primeros 20 bytes: {raw[:20]!r}")
print(f"  ultimos 30 bytes: {raw[-30:]!r}")
print()
df_year = pd.read_csv(p / "YEAR.csv")
print(f"  pandas: {len(df_year)} filas, dtype={df_year['VALUE'].dtype}")
print(f"  ultimos 5 valores: {df_year['VALUE'].tail().tolist()}")
print(f"  contiene 2055? {2055 in df_year['VALUE'].tolist()}")

# 2) DataPortal aislado: solo carga YEAR.csv sin nada mas
print("\n" + "=" * 70)
print("DataPortal aislado (solo YEAR.csv)")
print("=" * 70)
m_test = AbstractModel()
m_test.YEAR = Set(ordered=True)
data_test = DataPortal()
data_test.load(filename=str(p / "YEAR.csv"), set="YEAR")
inst_test = m_test.create_instance(data_test)
years_only = sorted(inst_test.YEAR)
print(f"  instance.YEAR (aislado): {len(years_only)} elementos")
print(f"  rango: {min(years_only)} -> {max(years_only)}")
print(f"  ultimos 5: {years_only[-5:]}")
print(f"  contiene 2055? {2055 in years_only}")

# 3) Comparar contra YearSplit (puede que haya validacion cruzada)
ys_path = p / "YearSplit.csv"
if ys_path.exists():
    df_ys = pd.read_csv(ys_path)
    ys_years = sorted(df_ys["YEAR"].unique().astype(int).tolist())
    print(f"\n  YearSplit.csv: {len(df_ys)} filas")
    print(f"  YearSplit YEARs unicos: {len(ys_years)}, rango {min(ys_years)}->{max(ys_years)}")
    print(f"  YearSplit contiene 2055? {2055 in ys_years}")
    if 2055 in df_year["VALUE"].tolist() and 2055 not in ys_years:
        print("\n  !! 2055 esta en YEAR.csv pero NO en YearSplit.csv")
        print("     -> al construir el modelo Pyomo, YearSplit[ts, 2055] no esta definido")
        print("     -> esto puede no ser el problema directo, pero es importante")

======================================================================
YEAR.csv: contenido raw
======================================================================
  bytes totales: 171
  primeros 20 bytes: b'VALUE\n2022\n2023\n2024'
  ultimos 30 bytes: b'2049\n2050\n2051\n2052\n2053\n2054\n'

  pandas: 33 filas, dtype=int64
  ultimos 5 valores: [2050, 2051, 2052, 2053, 2054]
  contiene 2055? False

======================================================================
DataPortal aislado (solo YEAR.csv)
======================================================================
  instance.YEAR (aislado): 33 elementos
  rango: 2022 -> 2054
  ultimos 5: [2050, 2051, 2052, 2053, 2054]
  contiene 2055? False

  YearSplit.csv: 33 filas
  YearSplit YEARs unicos: 33, rango 2022->2054
  YearSplit contiene 2055? False

In [88]:
instance

## 5. Etapa 4 — `solve_model`

`solve_model(instance, solver_name)` resuelve y devuelve un dict con `solver_name`, `solver_status`, `objective_value`. Internamente prueba el solver elegido y, si no está disponible, cae al siguiente.

**Solvers disponibles** según `SOLVER_FACTORIES` (en `solver.py`): `"highs"`, `"glpk"`, `"gurobi"`.

In [89]:
from app.simulation.core.solver import solve_model

# Cambia "gurobi" -> "highs" / "glpk" segun lo que necesites probar
SOLVER_NAME = "highs"

t0 = time.perf_counter()
solver_result = solve_model(instance, solver_name=SOLVER_NAME)
t_stage4 = time.perf_counter() - t0

print(f"Etapa 4 (solve_model) completada en {t_stage4:.2f} s")
print(f"  solver_name  : {solver_result['solver_name']}")
print(f"  solver_status: {solver_result['solver_status']}")
print(f"  objective    : {solver_result['objective_value']:.6e}")
if solver_result.get("solver_threads_used") is not None:
    print(f"  threads      : {solver_result['solver_threads_used']}")
if solver_result.get("infeasibility_diagnostics") is not None:
    diag = solver_result["infeasibility_diagnostics"]
    print(f"  -> infactibilidad detectada: {len(diag.get('constraint_violations', []))} constraints, {len(diag.get('var_bound_conflicts', []))} bounds")

No fue posible leer solver.threads desde BD; usando fallback=0
Traceback (most recent call last):
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3317, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/psycopg/connection.py", line 100, in connect
    attempts = conninfo_attempts(params)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/psycopg/_conninfo_attempts.py", line 55, in conninfo_attempts
    raise last_exc
psycopg.OperationalError: failed to resolve host 'db': [Errno 8] nodename nor servname provided, or not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/app/simulation/core/solver.py", line 193, in _resolve_solver_threads
    return SystemSettingsService.get_solver_threads(db, fallback=fallback)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/app/services/system_settings_service.py", line 71, in get_solver_threads
    return SystemSettingsService.get_int(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        db, SOLVER_THREADS_KEY, default=fallback
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/app/services/system_settings_service.py", line 35, in get_int
    row = SystemSettingsService.get_raw(db, key)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/backend/app/services/system_settings_service.py", line 29, in get_raw
    return db.execute(
           ~~~~~~~~~~^
        select(SystemSetting).where(SystemSetting.key == key)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ).scalar_one_or_none()
    ^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2351, in execute
    return self._execute_internal(
           ~~~~~~~~~~~~~~~~~~~~~~^
        statement,
        ^^^^^^^^^^
    ...<4 lines>...
        _add_event=_add_event,
        ^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2239, in _execute_internal
    conn = self._connection_for_bind(bind)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 2108, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/orm/state_changes.py", line 137, in _go
    ret_value = fn(self, *arg, **kw)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/orm/session.py", line 1187, in _connection_for_bind
    conn = bind.connect()
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3293, in connect
    return self._connection_cls(self)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 145, in __init__
    Connection._handle_dbapi_exception_noconnection(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        err, dialect, engine
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 2448, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 143, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/base.py", line 3317, in raw_connection
    return self.pool.connect()
           ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 448, in connect
    return _ConnectionFairy._checkout(self)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 1272, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 712, in checkout
    rec = pool._do_get()
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 177, in _do_get
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/impl.py", line 175, in _do_get
    return self._create_connection()
           ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 389, in _create_connection
    return _ConnectionRecord(self)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 674, in __init__
    self.__connect()
    ~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 900, in __connect
    with util.safe_reraise():
         ~~~~~~~~~~~~~~~~~^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/util/langhelpers.py", line 121, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/pool/base.py", line 896, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
                                         ~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/create.py", line 667, in connect
    return dialect.connect(*cargs_tup, **cparams)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/sqlalchemy/engine/default.py", line 630, in connect
    return self.loaded_dbapi.connect(*cargs, **cparams)  # type: ignore[no-any-return]  # NOQA: E501
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/psycopg/connection.py", line 100, in connect
    attempts = conninfo_attempts(params)
  File "/Users/davidbedoya0/Documents/UPME/Demanda/Repositorio/OSEMOSYS_FINAL_2/Osemosys_UPME/pen_venv/lib/python3.13/site-packages/psycopg/_conninfo_attempts.py", line 55, in conninfo_attempts
    raise last_exc
sqlalchemy.exc.OperationalError: (psycopg.OperationalError) failed to resolve host 'db': [Errno 8] nodename nor servname provided, or not known
(Background on this error at: https://sqlalche.me/e/20/e3q8)

Etapa 4 (solve_model) completada en 125.06 s
  solver_name  : highs
  solver_status: optimal
  objective    : 1.096825e+06

## 6. Etapa 5 — `process_results`

`process_results` extrae las variables óptimas (Dispatch, NewCapacity, AnnualEmissions, etc.) y las convierte a listas de dicts serializables (lo que la app guarda en `osemosys_output_param_value`).

**Aquí es donde puede aparecer el filtro de años** si la app y el notebook divergen.

In [90]:
from app.simulation.core.results_processing import process_results

sets = proc_result.sets

t0 = time.perf_counter()
results = process_results(
    instance,
    solver_result,
    regions=sets.get("REGION", []),
    technologies=sets.get("TECHNOLOGY", []),
    years=sets.get("YEAR", []),
    emissions=sets.get("EMISSION", []),
    has_storage=proc_result.has_storage,
    region_id_by_name=proc_result.region_id_by_name,
    technology_id_by_name=proc_result.technology_id_by_name,
    region_name_by_id=proc_result.region_name_by_id,
    fuel_id_by_name=proc_result.fuel_id_by_name,
    emission_id_by_name=proc_result.emission_id_by_name,
    timeslice_id_by_name=proc_result.timeslice_id_by_name,
    mode_of_operation_id_by_name=proc_result.mode_of_operation_id_by_name,
    season_id_by_name=proc_result.season_id_by_name,
    daytype_id_by_name=proc_result.daytype_id_by_name,
    dailytimebracket_id_by_name=proc_result.dailytimebracket_id_by_name,
    storage_id_by_name=proc_result.storage_id_by_name,
)
t_stage5 = time.perf_counter() - t0

print(f"Etapa 5 (process_results) completada en {t_stage5:.2f} s")
print(f"  objective_value: {results.get('objective_value')}")
print(f"  solver_status  : {results.get('solver_status')}")
print(f"  total_demand   : {results.get('total_demand')}")
print(f"  total_dispatch : {results.get('total_dispatch')}")
print(f"  total_unmet    : {results.get('total_unmet')}")
print(f"  coverage_ratio : {results.get('coverage_ratio')}")

# Conteos
for key in ("dispatch", "new_capacity", "unmet_demand", "annual_emissions"):
    n = len(results.get(key, []))
    print(f"  # {key:<18s}: {n}")

Etapa 5 (process_results) completada en 11.98 s
  objective_value: 1096825.0493798647
  solver_status  : optimal
  total_demand   : 34114.80109564094
  total_dispatch : 1183723.311498532
  total_unmet    : 0.0
  coverage_ratio : 1.0
  # dispatch          : 7896
  # new_capacity      : 13464
  # unmet_demand      : 33
  # annual_emissions  : 33

In [91]:
# CRITICO: inspeccionar que rango de anos hay en los outputs
print("Anos presentes en cada bloque de resultados:\n")

def _years_in(rows, year_key="year"):
    if not rows:
        return []
    years = set()
    for r in rows:
        y = r.get(year_key)
        if y is not None:
            years.add(int(y))
    return sorted(years)

for key in ("dispatch", "new_capacity", "unmet_demand", "annual_emissions"):
    rows = results.get(key, [])
    yrs = _years_in(rows)
    if yrs:
        print(f"  {key:<20s} {len(rows):>10d} filas | YEAR rango {min(yrs)} -> {max(yrs)} ({len(yrs)} anos unicos)")
    else:
        print(f"  {key:<20s} {len(rows):>10d} filas | sin YEAR")

# Tambien intermediate_variables si existe
inter = results.get("intermediate_variables", {}) or {}
print(f"\nintermediate_variables: {len(inter)} entradas")
for var_name, rows in list(inter.items())[:8]:
    yrs = _years_in(rows)
    if yrs:
        print(f"  {var_name:<35s} {len(rows):>10d} filas | YEAR {min(yrs)}->{max(yrs)}")
    else:
        print(f"  {var_name:<35s} {len(rows):>10d} filas | sin YEAR")

# Comparacion final
print(f"\n=== Comparacion final ===")
print(f"  proc_result.sets['YEAR']  : {min(years_proc)} -> {max(years_proc)} ({len(years_proc)} anos)")
print(f"  instance.YEAR             : {min(years_instance)} -> {max(years_instance)} ({len(years_instance)} anos)")
all_output_years = set()
for key in ("dispatch", "new_capacity", "unmet_demand", "annual_emissions"):
    all_output_years.update(_years_in(results.get(key, [])))
if all_output_years:
    print(f"  results (todos los blocks) : {min(all_output_years)} -> {max(all_output_years)} ({len(all_output_years)} anos)")

if all_output_years and years_proc:
    missing_in_results = set(years_proc) - all_output_years
    if missing_in_results:
        print(f"\n!! Anos en proc_result.sets[YEAR] pero NO en results: {sorted(missing_in_results)}")
        print("   -> el filtro esta entre instance/process_results.")
    else:
        print(f"\nOK: todos los anos de proc_result.sets[YEAR] estan en results.")

Anos presentes en cada bloque de resultados:

  dispatch                   7896 filas | YEAR rango 2022 -> 2054 (33 anos unicos)
  new_capacity              13464 filas | YEAR rango 2022 -> 2054 (33 anos unicos)
  unmet_demand                 33 filas | YEAR rango 2022 -> 2054 (33 anos unicos)
  annual_emissions             33 filas | YEAR rango 2022 -> 2054 (33 anos unicos)

intermediate_variables: 26 entradas
  RateOfActivity                            7897 filas | sin YEAR
  SalvageValue                              1434 filas | sin YEAR
  DiscountedSalvageValue                    1434 filas | sin YEAR
  OperatingCost                             7850 filas | sin YEAR
  CapitalInvestment                         2626 filas | sin YEAR
  DiscountedCapitalInvestment               2626 filas | sin YEAR
  DiscountedOperatingCost                   7832 filas | sin YEAR
  AnnualVariableOperatingCost                684 filas | sin YEAR

=== Comparacion final ===
  proc_result.sets['YEAR']  : 2022 -> 2054 (33 anos)
  instance.YEAR             : 2022 -> 2054 (33 anos)
  results (todos los blocks) : 2022 -> 2054 (33 anos)

OK: todos los anos de proc_result.sets[YEAR] estan en results.

## 7. Resumen de tiempos

Compara con los tiempos que reporta la app (en `simulation_job.metadata`).

In [92]:
print(f"{'Etapa':<35s} {'Segundos':>10s}")
print("-" * 48)
for name, val in [
    ("1. data_processing",      t_stage1),
    ("2. create_abstract_model", t_stage2),
    ("3. build_instance",        t_stage3),
    ("4. solve_model",           t_stage4),
    ("5. process_results",       t_stage5),
]:
    print(f"  {name:<33s} {val:>10.2f}")
total = t_stage1 + t_stage2 + t_stage3 + t_stage4 + t_stage5
print("-" * 48)
print(f"  {'TOTAL':<33s} {total:>10.2f}")

Etapa                                 Segundos
------------------------------------------------
  1. data_processing                      9.53
  2. create_abstract_model                0.01
  3. build_instance                      28.20
  4. solve_model                        125.06
  5. process_results                     11.98
------------------------------------------------
  TOTAL                                 174.77

In [93]:
df_capacity =results['new_capacity']
df_capacity = pd.DataFrame(df_capacity)
df_capacity

,region_id,technology_id,year,new_capacity,technology_name,region_name
0,1,1,2022,-0.0,BACKSTOP_1,RE1
1,1,1,2023,-0.0,BACKSTOP_1,RE1
2,1,1,2024,-0.0,BACKSTOP_1,RE1
3,1,1,2025,-0.0,BACKSTOP_1,RE1
4,1,1,2026,-0.0,BACKSTOP_1,RE1
...,...,...,...,...,...,...
13459,1,394,2050,-0.0,UPSSMRCCS,RE1
13460,1,394,2051,-0.0,UPSSMRCCS,RE1
13461,1,394,2052,-0.0,UPSSMRCCS,RE1
13462,1,394,2053,-0.0,UPSSMRCCS,RE1
13463,1,394,2054,-0.0,UPSSMRCCS,RE1

In [94]:
df_capacity[df_capacity['technology_name'].str.startswith('PWR')]

,region_id,technology_id,year,new_capacity,technology_name,region_name
11946,1,348,2022,-0.000,PWRAFR,RE1
11947,1,348,2023,-0.000,PWRAFR,RE1
11948,1,348,2024,-0.000,PWRAFR,RE1
11949,1,348,2025,-0.000,PWRAFR,RE1
11950,1,348,2026,-0.000,PWRAFR,RE1
...,...,...,...,...,...,...
12799,1,374,2050,-0.000,PWRWNDONS,RE1
12800,1,374,2051,-0.000,PWRWNDONS,RE1
12801,1,374,2052,31.536,PWRWNDONS,RE1
12802,1,374,2053,31.536,PWRWNDONS,RE1
12803,1,374,2054,31.536,PWRWNDONS,RE1

In [95]:
import numpy as np

In [96]:
data_TotalCapacityAnnual = results['intermediate_variables']['TotalCapacityAnnual']
df_TotalCapacityAnnual = pd.DataFrame(data_TotalCapacityAnnual)
df_TotalCapacityAnnual[['region', 'variable', 'anio']] = pd.DataFrame(df_TotalCapacityAnnual['index'].tolist(), index=df_TotalCapacityAnnual.index)
df_TotalCapacityAnnual

                       index      value region   variable  anio
0     [RE1, DEMAGFDSL, 2022]  21.391708    RE1  DEMAGFDSL  2022
1     [RE1, DEMAGFDSL, 2023]  21.750707    RE1  DEMAGFDSL  2023
2     [RE1, DEMAGFDSL, 2024]  23.484340    RE1  DEMAGFDSL  2024
3     [RE1, DEMAGFDSL, 2025]  24.353422    RE1  DEMAGFDSL  2025
4     [RE1, DEMAGFDSL, 2026]  25.021600    RE1  DEMAGFDSL  2026
...                      ...        ...    ...        ...   ...
9811  [RE1, UPSSMRCCS, 2050]  74.908559    RE1  UPSSMRCCS  2050
9812  [RE1, UPSSMRCCS, 2051]  74.908559    RE1  UPSSMRCCS  2051
9813  [RE1, UPSSMRCCS, 2052]  74.908559    RE1  UPSSMRCCS  2052
9814  [RE1, UPSSMRCCS, 2053]  74.908559    RE1  UPSSMRCCS  2053
9815  [RE1, UPSSMRCCS, 2054]  74.908559    RE1  UPSSMRCCS  2054

[9816 rows x 5 columns]

In [97]:
df_TotalCapacityAnnual[df_TotalCapacityAnnual['variable'].str.startswith('PWR')].groupby('anio')['value'].sum().reset_index()

    anio        value
0   2022   593.130216
1   2023   656.701430
2   2024   679.827785
3   2025   699.861190
4   2026   760.984672
5   2027   893.517642
6   2028   930.698315
7   2029   948.913285
8   2030   991.630234
9   2031  1002.464213
10  2032  1017.077557
11  2033  1045.504298
12  2034  1175.666651
13  2035  1301.225439
14  2036  1437.791776
15  2037  1569.156099
16  2038  1730.391343
17  2039  1914.095405
18  2040  2139.765995
19  2041  2217.836321
20  2042  2358.346306
21  2043  2497.295831
22  2044  2608.134836
23  2045  2678.983942
24  2046  2888.970116
25  2047  3134.439374
26  2048  3334.674198
27  2049  3525.246568
28  2050  3706.266930
29  2051  3811.328162
30  2052  3960.906962
31  2053  4041.957508
32  2054  4122.175714